name: "🔧 Enhancement request"
description: Create a new ticket for an enhancement.
title: "🔧 [ENH] - <title>"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🔧 Enhancement request
        Please provide a clear and concise description of what the bug is.
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter an explicit description of your issue
      placeholder: Short and explicit description of your incident...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: Please enter an explicit description of your issue
      placeholder: |
        A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: "Actual Behavior"
      description: Please enter an explicit description of your issue
      placeholder: |
        A clear and concise description of what actually happened.
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: Please enter an explicit description of your issue
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: bash
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Additional Information
        Please provide any additional information that may help us diagnose the issue.
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: If applicable, add screenshots to help explain your problem.
      value: |
        ![DESCRIPTION](LINK.png)
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: "Version"
      description: What version of the software are you testing ?
      placeholder: 1.0.0
  - type: input
    id: module
    attributes:
      label: "Module"
      description: What module is the bug related to ?
      placeholder: |
        Authentication, User Management, Invoice
  - type: dropdown
    id: devices
    attributes:
      label: "Devices"
      description: What devices are you seeing the problem on ?
      multiple: true
      options:
        - "Desktop"
        - "Mobile"
        - "Tablet"
