name: Pre Deploy
description: "Composite action for pre-deploy checks"
inputs: {}
runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24
    - name: Install dependencies
      run: go mod tidy
      shell: bash
    - name: Run tests
      run: go test ./...
      shell: bash
    - name: Lint
      uses: golangci/golangci-lint-action@v6
