apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ingress.fullname" . }}
  labels:
    {{- include "deployment.labels" . | nindent 4 }}
  annotations: 
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts: {{.Values.ingress.host}}
      secretName: {{ include "ingress.secretName" . }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          {{- range .Values.ingress.paths }}
          - path: {{ .path }}
            {{- with .pathType }}
            pathType: {{ . }}
            {{- end }}
            backend:
              service:
                name: {{ include "service.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
