apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secret.fullname" . }}
type: Opaque
data: 
  {{- with .Values.secrets }}
  {{- range $key, $val := . }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
  {{- end }}